const HOUR = 3600000;
const DAY = 86400000;

function at(daysFromNow, hour = 23, minute = 59) {
  const d = new Date(Date.now() + daysFromNow * DAY);
  d.setHours(hour, minute, 0, 0);
  return d.toISOString();
}

export const DEMO_MODULES = [
  { code: 'ET0421', name: 'Embedded Systems Design', lecturer: 'Dr. Lim Wei Ming', color: 'brand' },
  {
    code: 'IT2154',
    name: 'Web Application Development',
    lecturer: 'Ms. Priya Raman',
    color: 'violet',
  },
  {
    code: 'MA1002',
    name: 'Engineering Mathematics II',
    lecturer: 'Mr. Tan Kok Leong',
    color: 'emerald',
  },
  {
    code: 'CS2043',
    name: 'Data Structures & Algorithms',
    lecturer: 'Dr. Sarah Chen',
    color: 'amber',
  },
];

export const DEMO_TASKS = [
  {
    id: 'task_emb_lab',
    title: 'Lab 4 Report — PWM Motor Control',
    moduleCode: 'ET0421',
    moduleName: 'Embedded Systems Design',
    taskType: 'Practical',
    deadline: at(2, 23, 59),
    hours: 8,
    weightage: 20,
    isGroup: false,
    progress: 25,
    status: 'In Progress',
    notes: 'Include oscilloscope screenshots and duty-cycle calculations for all three test cases.',
    subtasks: [
      {
        id: 'st_1',
        title: 'Capture oscilloscope readings',
        hours: 1.5,
        done: true,
        dueDate: at(0),
      },
      { id: 'st_2', title: 'Write methodology section', hours: 2, done: false, dueDate: at(1) },
      {
        id: 'st_3',
        title: 'Plot duty cycle vs RPM graphs',
        hours: 2.5,
        done: false,
        dueDate: at(1),
      },
      { id: 'st_4', title: 'Conclusion + proofread', hours: 2, done: false, dueDate: at(2, 18) },
    ],
    createdAt: new Date(Date.now() - 6 * DAY).toISOString(),
    updatedAt: new Date(Date.now() - 2 * HOUR).toISOString(),
  },
  {
    id: 'task_web_midterm',
    title: 'Mid-Semester Practical Test',
    moduleCode: 'IT2154',
    moduleName: 'Web Application Development',
    taskType: 'Test',
    deadline: at(3, 9, 0),
    hours: 10,
    weightage: 30,
    isGroup: false,
    progress: 40,
    status: 'In Progress',
    notes: 'Covers React hooks, REST integration, and responsive layout. Closed book, 2 hours.',
    subtasks: [
      { id: 'st_5', title: 'Revise React hooks & state', hours: 3, done: true, dueDate: at(0) },
      {
        id: 'st_6',
        title: 'Practice fetch + error handling',
        hours: 2.5,
        done: true,
        dueDate: at(1),
      },
      {
        id: 'st_7',
        title: 'Rebuild past-year layout task',
        hours: 2.5,
        done: false,
        dueDate: at(2),
      },
      { id: 'st_8', title: 'Timed mock attempt', hours: 2, done: false, dueDate: at(2, 20) },
    ],
    createdAt: new Date(Date.now() - 9 * DAY).toISOString(),
    updatedAt: new Date(Date.now() - 5 * HOUR).toISOString(),
  },
  {
    id: 'task_iot_project',
    title: 'Smart Campus Project — Phase 2 Submission',
    moduleCode: 'ET0421',
    moduleName: 'Embedded Systems Design',
    taskType: 'Project',
    deadline: at(6, 23, 59),
    hours: 18,
    weightage: 25,
    isGroup: true,
    progress: 30,
    status: 'In Progress',
    notes: 'My scope: sensor node firmware + MQTT publishing. Jason handles the dashboard.',
    subtasks: [
      {
        id: 'st_9',
        title: 'Finalise sensor wiring schematic',
        hours: 3,
        done: true,
        dueDate: at(1),
      },
      {
        id: 'st_10',
        title: 'Write firmware for DHT22 + LDR',
        hours: 5,
        done: false,
        dueDate: at(3),
      },
      {
        id: 'st_11',
        title: 'Publish readings to MQTT broker',
        hours: 4,
        done: false,
        dueDate: at(4),
      },
      { id: 'st_12', title: 'Individual reflection report', hours: 3, done: false, dueDate: at(5) },
      { id: 'st_13', title: 'Record 3-min demo video', hours: 3, done: false, dueDate: at(6, 18) },
    ],
    createdAt: new Date(Date.now() - 14 * DAY).toISOString(),
    updatedAt: new Date(Date.now() - 8 * HOUR).toISOString(),
  },
  {
    id: 'task_dsa_assign',
    title: 'Assignment 3 — Graph Traversal',
    moduleCode: 'CS2043',
    moduleName: 'Data Structures & Algorithms',
    taskType: 'Assignment',
    deadline: at(4, 23, 59),
    hours: 6,
    weightage: 15,
    isGroup: false,
    progress: 0,
    status: 'Pending',
    notes: 'Implement BFS and DFS with adjacency lists. Include Big-O analysis.',
    subtasks: [],
    createdAt: new Date(Date.now() - 3 * DAY).toISOString(),
    updatedAt: new Date(Date.now() - 3 * DAY).toISOString(),
  },
  {
    id: 'task_math_tut',
    title: 'Tutorial 8 — Laplace Transforms',
    moduleCode: 'MA1002',
    moduleName: 'Engineering Mathematics II',
    taskType: 'Assignment',
    deadline: at(9, 23, 59),
    hours: 3,
    weightage: 5,
    isGroup: false,
    progress: 0,
    status: 'Pending',
    notes: '',
    subtasks: [],
    createdAt: new Date(Date.now() - DAY).toISOString(),
    updatedAt: new Date(Date.now() - DAY).toISOString(),
  },
  {
    id: 'task_web_pitch',
    title: 'Client Pitch Presentation',
    moduleCode: 'IT2154',
    moduleName: 'Web Application Development',
    taskType: 'Presentation',
    deadline: at(12, 10, 0),
    hours: 5,
    weightage: 10,
    isGroup: true,
    progress: 0,
    status: 'Pending',
    notes: '8 minutes + 4 minutes Q&A. Slides due to lecturer the night before.',
    subtasks: [],
    createdAt: new Date(Date.now() - DAY).toISOString(),
    updatedAt: new Date(Date.now() - DAY).toISOString(),
  },
  {
    id: 'task_emb_quiz',
    title: 'Quiz 2 — Interrupts & Timers',
    moduleCode: 'ET0421',
    moduleName: 'Embedded Systems Design',
    taskType: 'Test',
    deadline: at(-3, 11, 0),
    hours: 3,
    weightage: 10,
    isGroup: false,
    progress: 100,
    status: 'Completed',
    notes: 'Scored 88%.',
    subtasks: [],
    createdAt: new Date(Date.now() - 10 * DAY).toISOString(),
    updatedAt: new Date(Date.now() - 3 * DAY).toISOString(),
  },
  {
    id: 'task_dsa_quiz',
    title: 'Quiz 1 — Sorting Complexity',
    moduleCode: 'CS2043',
    moduleName: 'Data Structures & Algorithms',
    taskType: 'Test',
    deadline: at(-8, 14, 0),
    hours: 2,
    weightage: 5,
    isGroup: false,
    progress: 100,
    status: 'Completed',
    notes: '',
    subtasks: [],
    createdAt: new Date(Date.now() - 15 * DAY).toISOString(),
    updatedAt: new Date(Date.now() - 8 * DAY).toISOString(),
  },
];

export const DEMO_USER = {
  userId: 'demo-user',
  name: 'Alex Tan',
  email: 'demo@polytrack.app',
  institution: 'Nanyang Polytechnic',
  course: 'Diploma in Engineering with Business',
  dailyHours: 4,
  isDemo: true,
  notifications: { push: true, email: true, quietHours: true },
};
